name: college_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  dots_indicator: ^2.1.0
  flutter_launcher_icons: ^0.9.3
  file_picker: ^4.6.1
  get_storage: ^2.0.3
  dio: ^4.0.6
  dartz: ^0.10.1
  loading_overlay: ^0.3.0
  connectivity: ^3.0.6
  pluto_grid: ^5.4.9
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.1.7
  dropdown_button2: ^1.9.2
  awesome_dialog: ^3.0.2
  flutter_staggered_grid_view: ^0.6.2
dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/png/launcher.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/jpg/
  fonts:
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-Bold.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
